# Generated by Django 3.1.6 on 2022-03-14 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20220314_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='due',
            field=models.DateTimeField(default=datetime.date(2022, 3, 21)),
        ),
    ]
