# Generated by Django 3.1.6 on 2022-03-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20220314_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='trade.customermodel'),
        ),
    ]
