# Generated by Django 3.1.6 on 2022-03-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20220314_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='trade.invoicemodel'),
        ),
    ]
